# Generated by Django 6.0.7 on 2026-08-09 08:29

import app.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricBenchmarkRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('total_trials', models.IntegerField(default=0)),
                ('genuine_trials', models.IntegerField(default=0)),
                ('impostor_trials', models.IntegerField(default=0)),
                ('spoof_trials', models.IntegerField(default=0)),
                ('eer_score', models.FloatField(default=0.0)),
                ('eer_threshold', models.FloatField(default=0.75)),
                ('auc_roc', models.FloatField(default=0.0)),
                ('apcer', models.FloatField(default=0.0)),
                ('bpcer', models.FloatField(default=0.0)),
                ('acer', models.FloatField(default=0.0)),
                ('avg_latency_ms', models.FloatField(default=0.0)),
                ('details_json', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('account_number', models.CharField(default=app.models.generate_account_number, max_length=12, unique=True)),
                ('phone_number', models.CharField(blank=True, default='+1 (555) 019-2834', max_length=20)),
                ('checking_balance', models.DecimalField(decimal_places=2, default=Decimal('15840.50'), max_digits=14)),
                ('savings_balance', models.DecimalField(decimal_places=2, default=Decimal('42300.00'), max_digits=14)),
                ('investment_balance', models.DecimalField(decimal_places=2, default=Decimal('28750.75'), max_digits=14)),
                ('voice_enrolled', models.BooleanField(default=False)),
                ('voice_enrolled_at', models.DateTimeField(blank=True, null=True)),
                ('voice_login_enabled', models.BooleanField(default=True)),
                ('security_level', models.CharField(choices=[('STANDARD', 'Standard Security (Password + Optional Voice)'), ('HIGH', 'High Security (Voice Step-Up on Transfers > $1,000)'), ('STRICT', 'Strict Treasury Grade (Voice Required for All Transactions)')], default='HIGH', max_length=20)),
                ('risk_tier', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk')], default='LOW', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('account_number', models.CharField(max_length=20)),
                ('bank_name', models.CharField(default='Apex Federal Bank', max_length=100)),
                ('routing_number', models.CharField(default='021000021', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_verified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BiometricAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_type', models.CharField(choices=[('LOGIN', 'Voice Biometric Login'), ('STEP_UP_TRANSACTION', 'High-Value Transaction Step-Up'), ('BENEFICIARY_ADD', 'Beneficiary Addition Step-Up'), ('RE_ENROLLMENT', 'Voiceprint Enrollment / Update'), ('TEST_VERIFY', 'Diagnostic Voice Verification')], default='LOGIN', max_length=30)),
                ('challenge_phrase', models.CharField(max_length=255)),
                ('spoken_transcript', models.CharField(blank=True, max_length=255)),
                ('similarity_score', models.FloatField(default=0.0)),
                ('threshold_used', models.FloatField(default=0.75)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('liveness_score', models.FloatField(default=0.0)),
                ('snr_db', models.FloatField(default=0.0)),
                ('decision', models.CharField(choices=[('ACCEPTED', 'Biometric Match Accepted'), ('REJECTED', 'Voiceprint Mismatch Rejected'), ('SPOOF_DETECTED', 'Presentation Attack Detected'), ('POOR_AUDIO', 'Unusable Acoustic Quality'), ('ERROR', 'Processing Error')], default='ACCEPTED', max_length=20)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('attack_type', models.CharField(default='NONE', max_length=50)),
                ('latency_ms', models.FloatField(default=0.0)),
                ('client_ip', models.CharField(default='127.0.0.1', max_length=45)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biometric_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True)),
                ('recipient_name', models.CharField(max_length=150)),
                ('recipient_account', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('category', models.CharField(choices=[('TRANSFER', 'Direct Transfer'), ('WIRE', 'High-Value Wire Transfer'), ('BILL_PAY', 'Bill Payment'), ('INSTANT', 'Instant Voice Cash')], default='TRANSFER', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('PENDING_VOICE_AUTH', 'Pending Voice Authorization'), ('REJECTED', 'Biometric Auth Rejected'), ('CANCELLED', 'Cancelled')], default='COMPLETED', max_length=25)),
                ('step_up_required', models.BooleanField(default=False)),
                ('voice_auth_score', models.FloatField(blank=True, null=True)),
                ('voice_auth_confidence', models.FloatField(blank=True, null=True)),
                ('challenge_phrase_used', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoiceprintProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding_vector', models.JSONField(default=list, help_text='192-dimensional L2 normalized acoustic vector')),
                ('enrollment_passphrase', models.CharField(default='My voice is my secure key for Apex Bank', max_length=255)),
                ('sample_count', models.IntegerField(default=0)),
                ('intra_variance_score', models.FloatField(default=0.0, help_text='Intra-speaker sample consistency variance')),
                ('baseline_f0_hz', models.FloatField(default=125.0)),
                ('baseline_jitter', models.FloatField(default=0.85)),
                ('baseline_spectral_centroid', models.FloatField(default=2250.0)),
                ('voiceprint_hash', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active & Verified'), ('PENDING', 'Enrollment Incomplete'), ('REVOKED', 'Revoked / Re-enrollment Required')], default='PENDING', max_length=20)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VoiceEnrollmentSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_index', models.IntegerField(default=1)),
                ('passphrase', models.CharField(max_length=255)),
                ('audio_duration', models.FloatField(default=0.0)),
                ('snr_db', models.FloatField(default=0.0)),
                ('embedding_json', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='app.voiceprintprofile')),
            ],
            options={
                'ordering': ['sample_index'],
            },
        ),
    ]
