# Generated by Django 6.0.7 on 2026-08-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('appointment_request', 'Appointment Request'), ('appointment_response', 'Appointment Response'), ('task_assigned', 'Task Assigned'), ('task_completed', 'Task Completed'), ('project_invite', 'Project Invitation'), ('workspace_invite', 'Workspace Invitation'), ('comment_mention', 'Comment Mention'), ('system_alert', 'System Alert')], default='system_alert', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='object_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
