# Generated by Django 6.0.7 on 2026-08-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('voice_auth_approved', 'Voice Authentication Approved'), ('voice_auth_failed', 'Voice Authentication Rejected / Alert'), ('voiceprint_enrolled', 'Voiceprint Enrolled / Updated'), ('wire_transfer_processed', 'Wire Transfer Processed'), ('security_alert', 'Security & Biometrics Alert'), ('system_alert', 'System Alert')], default='system_alert', max_length=50),
        ),
    ]
